name: xivlauncher

on:
  push:
    paths:
      - PKGBUILD
  pull_request:
    branches:
      - main
    paths:
      - PKGBUILD
  workflow_dispatch:
    inputs:
      aur:
        description: 'Push to AUR?'
        required: false
        default: 'false'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/centzilius/arch-makepkg:latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare workspace
        run: |
          mkdir /home/builder/workspace
          rsync -ahvP /__w/aur-xivlauncher/aur-xivlauncher/ /home/builder/workspace/
          chown -R builder:builder /home/builder/
      - name: Build package
        run: |
          cd /home/builder/workspace
          sudo -u builder makepkg -scf --noconfirm
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: xivlauncher
          path: /home/builder/workspace/*.pkg.tar.zst
          if-no-files-found: error
  aur:
    needs: build
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event.inputs.aur == 'true' }}
    runs-on: ubuntu-latest
    container: ghcr.io/centzilius/arch-makepkg:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Checkout AUR
        run: |
          cd ~
          mkdir -p .ssh
          chmod 700 .ssh
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          echo "${{ secrets.ssh_key }}" > ~/.ssh/id_ed25519
          chmod 500 ~/.ssh/*
          ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub
          cd /tmp
          git clone ssh://aur@aur.archlinux.org/xivlauncher.git aur
      - name: Copy files
        run: |
          rsync -ahvP $GITHUB_WORKSPACE/aur-xivlauncher/{PKGBUILD,XIVLauncher.desktop} /tmp/aur/
      - name: Generate .SRCINFO
        run: |
          cd /tmp/aur/
          makepkg --printsrcinfo | tee .SRCINFO
      - name: Push
        run: |
          cd /tmp/aur/
          git add --all
          git commit -m 'sync from github'
          git push -u origin master
