name: xivlauncher

on:
  push:
    paths:
      - PKGBUILD
  pull_request:
    branches:
      - main
    paths:
      - PKGBUILD
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/centzilius/arch-makepkg:latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare workspace
        run: |
          mkdir /home/builder/workspace
          rsync -ahvP ${{ github.workspace}}/ /home/builder/workspace
      - name: Build package
        run:
          cd /home/builder/workspace
          sudo -u builder makepkg -scf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: xivlauncher
          path: /home/builder/workspace/*.pkg.tar.zst
          if-no-files-found: error